'use client';

import { useState } from 'react';
import { X, FileText, Download, FileSpreadsheet } from 'lucide-react';
import jsPDF from 'jspdf';
import { Issue, CrawlScore, Site } from '@/types';

interface ExportReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  site?: Site;
  score?: CrawlScore;
  issues?: Issue[];
}

export default function ExportReportModal({ isOpen, onClose, site, score, issues }: ExportReportModalProps) {
  const [includeCriticalOnly, setIncludeCriticalOnly] = useState(false);
  const [format, setFormat] = useState<'pdf' | 'csv'>('pdf');
  const [isExporting, setIsExporting] = useState(false);

  if (!isOpen) return null;

  const handleExportCSV = () => {
    if (!issues) return;
    const filtered = includeCriticalOnly ? issues.filter(i => i.severity === 'CRITICAL') : issues;

    const headers = ['Rule ID', 'Severity', 'Category', 'Title', 'Description', 'Recommendation', 'Affected URL'];
    const rows = filtered.map(i => [
      i.rule_id,
      i.severity,
      i.category,
      `"${i.title.replace(/"/g, '""')}"`,
      `"${i.description.replace(/"/g, '""')}"`,
      `"${i.recommendation.replace(/"/g, '""')}"`,
      `"${i.affected_url}"`
    ]);

    const csvContent = 'data:text/csv;charset=utf-8,' + [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `CrawlIQ_SEO_Audit_${site?.name || 'Report'}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleExportPDF = () => {
    setIsExporting(true);
    setTimeout(() => {
      const doc = new jsPDF();
      const title = site ? `SEO Audit Report - ${site.name}` : 'SEO Audit Report';

      doc.setFontSize(20);
      doc.setTextColor(30, 41, 59);
      doc.text(title, 14, 22);

      doc.setFontSize(10);
      doc.setTextColor(100, 116, 139);
      doc.text(`Generated by CrawlIQ on ${new Date().toLocaleDateString()}`, 14, 30);

      if (score) {
        doc.setFontSize(14);
        doc.setTextColor(15, 23, 42);
        doc.text(`Overall SEO Health Score: ${score.overall_score}/100`, 14, 45);

        doc.setFontSize(11);
        doc.text(`Meta Score: ${score.meta_score}/100`, 14, 55);
        doc.text(`Content Score: ${score.content_score}/100`, 14, 62);
        doc.text(`Performance Score: ${score.performance_score}/100`, 14, 69);
        doc.text(`Indexability Score: ${score.indexability_score}/100`, 14, 76);
      }

      if (issues && issues.length > 0) {
        doc.setFontSize(14);
        doc.text('Key Issues Found:', 14, 92);

        let y = 102;
        const targetIssues = includeCriticalOnly ? issues.filter(i => i.severity === 'CRITICAL') : issues;

        targetIssues.slice(0, 10).forEach((iss, idx) => {
          if (y > 270) {
            doc.addPage();
            y = 20;
          }
          doc.setFontSize(11);
          doc.setTextColor(15, 23, 42);
          doc.text(`${idx + 1}. [${iss.severity}] ${iss.title}`, 14, y);
          doc.setFontSize(9);
          doc.setTextColor(100, 116, 139);
          doc.text(`Fix: ${iss.recommendation.slice(0, 85)}...`, 20, y + 6);
          y += 16;
        });
      }

      doc.save(`CrawlIQ_SEO_Audit_${site?.name || 'Report'}.pdf`);
      setIsExporting(false);
      onClose();
    }, 600);
  };

  const handleExport = () => {
    if (format === 'csv') {
      handleExportCSV();
      onClose();
    } else {
      handleExportPDF();
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md p-4 animate-fade-in">
      <div className="bg-[#16161a] border border-[#242429] rounded-2xl w-full max-w-lg shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-[#242429]">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-[#ff5733]/10 border border-[#ff5733]/20 text-[#ff5733] flex items-center justify-center">
              <Download className="w-5 h-5" />
            </div>
            <h2 className="font-bold text-white text-lg tracking-tight">Export SEO Audit Report</h2>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-white p-1.5 rounded-xl hover:bg-[#202025]">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-5">
          <div>
            <label className="block text-xs font-semibold text-slate-300 uppercase tracking-wider mb-2">
              Export Format
            </label>
            <div className="grid grid-cols-2 gap-3">
              <button
                type="button"
                onClick={() => setFormat('pdf')}
                className={`p-3.5 rounded-xl border flex items-center gap-3 transition-all ${
                  format === 'pdf'
                    ? 'bg-[#ff5733]/20 border-[#ff5733] text-white font-bold'
                    : 'bg-[#101012] border-[#202025] text-slate-400 hover:bg-[#202025]'
                }`}
              >
                <FileText className={`w-5 h-5 ${format === 'pdf' ? 'text-[#ff5733]' : 'text-slate-400'}`} />
                <span className="text-xs">Executive PDF</span>
              </button>

              <button
                type="button"
                onClick={() => setFormat('csv')}
                className={`p-3.5 rounded-xl border flex items-center gap-3 transition-all ${
                  format === 'csv'
                    ? 'bg-[#ff5733]/20 border-[#ff5733] text-white font-bold'
                    : 'bg-[#101012] border-[#202025] text-slate-400 hover:bg-[#202025]'
                }`}
              >
                <FileSpreadsheet className={`w-5 h-5 ${format === 'csv' ? 'text-[#ff5733]' : 'text-slate-400'}`} />
                <span className="text-xs">Raw CSV Data</span>
              </button>
            </div>
          </div>

          <div className="flex items-center gap-3 pt-2">
            <input
              type="checkbox"
              id="criticalOnly"
              checked={includeCriticalOnly}
              onChange={(e) => setIncludeCriticalOnly(e.target.checked)}
              className="w-4 h-4 rounded text-[#ff5733] bg-[#101012] border-[#202025] focus:ring-[#ff5733]"
            />
            <label htmlFor="criticalOnly" className="text-xs text-slate-300 cursor-pointer font-medium">
              Export only Critical Severity issues
            </label>
          </div>

          {/* Action buttons */}
          <div className="flex items-center justify-end gap-3 pt-4 border-t border-[#242429]">
            <button
              onClick={onClose}
              className="px-4 py-2.5 text-xs font-semibold text-slate-400 hover:text-white bg-[#202025] hover:bg-[#2a2a30] rounded-xl transition-all"
            >
              Cancel
            </button>
            <button
              onClick={handleExport}
              disabled={isExporting}
              className="px-5 py-2.5 text-xs font-bold text-white bg-[#ff5733] hover:bg-[#e04826] rounded-xl shadow-lg shadow-[#ff5733]/20 transition-all flex items-center gap-2"
            >
              <Download className="w-4 h-4" />
              {isExporting ? 'Generating File...' : 'Download Report'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
